### ISSUE TITLE
Obtaining test certificate and key files

### ISSUE THREAD

**Issue by Kojonkler** [pkortekaas/wus-js#1]
Hi!

I am currently using your WUS 2.0 connector and trying to set up a connection to Digipoort using the **pre-production** environment to start developing our connection before we switch over to the production certificates. I saw in your codebase that you have generated your own certificate (`/certificate.crt`), but when generating my own one with the openSSL command, it did not work.

I generated my key like this: `openssl req -x509 -newkey rsa:2018 -keyout wus-test.key -out wus-test.crt -sha256 -days 365`

and I get the following response:

```
[08:31:27.18 INF] RunWusProcessor:start
[08:31:27.19 INF] Configuration used: preprod
[08:31:27.19 DBG] WusHttpClient:ctor start
[08:31:27.19 DBG] WusHttpClient:ctor start
[08:31:27.19 DBG] WusProcessor:ctor start
[08:31:27.19 DBG] WusResponse:ctor start
[08:31:27.19 DBG] WusResponse:ctor end
[08:31:27.19 DBG] WusDocument:ctor start
[08:31:27.19 DBG] WusDocument:ctor end
[08:31:27.19 DBG] WusProcessor:ctor end
[08:31:27.19 INF] -------------------- Deliver --------------------
[08:31:27.19 DBG] WusProcessor:Deliver start
[08:31:27.21 DBG] WusDocument:CreateDocument start
[08:31:27.21 DBG] WusDocument:SignXml start
[08:31:27.24 DBG] WusDocument:SignXml end
[08:31:27.24 DBG] WusDocument:CreateDocument end
[08:31:27.24 DBG] WusHttpClient:Post
Error: write EPROTO A81F0000:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1590:SSL alert number 42

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16) {
  errno: -4046,
  code: 'EPROTO',
  syscall: 'write'
}
```

My `config.json` is setup like this:

```
{
  "active": "preprod",
  "certificate": "wus-test.crt",
  "privatekey": "wus-test.key",
  "passphrase": "1234",
  "tracefile": null,
  "timeout": 60000,
  "preprod": {
    "delivery_url": "https://preprod-dgp2.procesinfrastructuur.nl/wus/2.0/aanleverservice/1.2",
    "status_url": "https://preprod-dgp2.procesinfrastructuur.nl/wus/2.0/statusinformatieservice/1.2",
    "ca": "./cert/kpn-pkioverheid-server-ca2020.pem",
    "fingerprint": "0B:F5:0D:F1:80:BA:02:7D:D3:E9:69:A8:67:7C:2E:A3:EA:2A:89:81"
  }
}
```

Do you happen to know what I am missing? Can we use our own generated `.crt` and `.key` files or do we have to obtain these files from a verified provider, such as KPN or QuoVadis, like we did for our production environment?

Thanks in advance!

**Comment by pkortekaas** [comment]
Hi

The self signed certificate in the codebase is only used for unit-testing the XML-DSig functionality. In order to actually connect to Digipoort you either need a qualified PKIo certificate or a Logius testcertificate that can be obtained for free:

`To use Digipoort and the Aansluit Suite Digipoort you need a digital certificate. For the Digipoort production environment you need a PKIoverheid certificate. These certificates can be requested at one of the qualified Certificate Service Providers (CSP). For the list of CSP’s see the Logius website. When connecting to the Aansluit Suite Service or the Digipoort Preproduction environment you can either use a PKIoverheid certificate or a Logius testcertificate. The Logius testcertificate is free and can be requested by sending an e-mail to servicecentrum@logius.nl. Send your company name, a company identification number and a company website or server address.`

More info can be found at [Logius Aansluit Suite](https://aansluiten.procesinfrastructuur.nl/) where you can also register for free to obtain all kind of additional information.
